version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-18-3
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  brakeman:
    enabled: true
checks:
  similar-code:
    enabled: false
exclude_patterns:
  - ".bundle/"
  - "babel.config.js"
  - "spec/"
  - "db/"
  - "bin/"
  - "config/"
  - "public/"
  - "vendor/"
  - "node_modules/"
  - "**/*.md"